### ISSUE TITLE
Ask for tutorials

### ISSUE THREAD

**Issue by qixuxiang** [grandemk/qemu_devices#1]
Hi, thanks for sharing the PCI virtual device code of the QEMU.
I recently is re-implementing a similar module. However, it seems hard to find some theoretical or detail materials about the design of a custom device for QEMU. I want to query is there any doc or tutorials for readers,3Q!

**Comment by grandemk** [comment]
I have explained this code in this article:
https://tic-le-polard.blogspot.fr/2015/01/emulate-pci-device-with-qemu.html
You can read the sources too. There isn't a lot of documentation so most of it I got reading the source code of other pci emulated devices. (this was in 2015 so you might have more luck than me finding other resources now)

**Comment by qixuxiang** [comment]
THX,,I am a fresh man,I'm afraid I need to add it to qemu source code and compile it,but I don't know the exact step.Would you please help me ? It is indeed double happiness for me to konw how to emulate a PCI device by modifying qemu source code step by step. Thanks a lot!

**Comment by qixuxiang** [comment]
THX,I am a fresh man,I'm afraid I need to add it to qemu source code and compile it,but I don't know the exact step.Would you please help me ? It is indeed double happiness for me to konw how to emulate a PCI device by modifying qemu source code step by step. Thanks a lot!

**Comment by grandemk** [comment]
Were you able to achieve it ?
